name: Build and Package VncClass

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages VncClass (Client)
        run: dotnet restore VncClass/VncClass.csproj
      
      - name: Restore NuGet packages VncClassManager (Server)
        run: dotnet restore VncClassManager/VncClassManager.csproj

      - name: Build VncClass (Client)
        run: msbuild VncClass/VncClass.csproj /p:Configuration=Release

      - name: Build VncClassManager (Server)
        run: msbuild VncClassManager/VncClassManager.csproj /p:Configuration=Release

      - name: Package Artifacts
        run: |
          mkdir artifacts
          Copy-Item "VncClass\bin\Release\*.exe" -Destination artifacts
          Copy-Item "VncClassManager\bin\Release\*.exe" -Destination artifacts

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: VncClass Build
          path: artifacts
